apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: playground-ingress
spec:
  defaultBackend:
      service:
        name: playground
        port:
          number: 8888
    - host:
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: playground
              port:
                number: 8888