apiVersion: v1
kind: Service
metadata:
  labels:
    app: playground
  name: playground-service
spec:
  type: ClusterIP
  selector:
    app: playground
  ports:
      - port: 8888
        targetPort: 8888
  # ports:
  # - name: http
  #   port: 80
  #   protocol: TCP
  #   targetPort: 80